#!/python
# -*- coding: utf-8 -*-

adherents = list()
actions = list()
for n in range(55) :
    adherents.append(n)
for n in range(22) :
    actions.append(n)
adherents[0]  = "AL - 813\nAlpes Provence"
adherents[1]  = "AM - 879\nAnjou Maine"
adherents[2]  = "AO - 872\nAlsace Vosges"
adherents[3]  = "AP - 881\ndes Savoies"
adherents[4]  = "AQ - 833\nAquitaine"
adherents[5]  = "AV - 847\nAtlantique Vendée"
adherents[6]  = "BI - 887\nBrie Picardie"
adherents[7]  = "BP - 868\nCentre France"
adherents[8]  = "CA - 822\nCôtesd'Armor"
adherents[9]  = "CE - 824\nCharente Périgord"
adherents[10] = "CL - 848\nCentre Loire"
adherents[11] = "CO - "
adherents[12] = "CP - 891\nProvence côte d'Azur"
adherents[13] = "CR - "
adherents[14] = "CS - 817\nCharente maritime deux Sêvres"
adherents[15] = "DP - 764\nChalus"
adherents[16] = "FC - "
adherents[17] = "FI - "
adherents[18] = "GU - "
adherents[19] = "IF - 882\nParis Île de France"
adherents[20] = "IV - 836\nÎle et Vilaine"
adherents[21] = "JP - 810\nChampagne Bourgogne"
adherents[22] = "KP - "
adherents[23] = "LA - "
adherents[24] = "LO - "
adherents[25] = "LP - 878\nCentre Est"
adherents[26] = "MA - "
adherents[27] = "MO - "
adherents[28] = "NE - "
adherents[29] = "NF - "
adherents[30] = "NM - 812\nNord Midi Pyrénées"
adherents[31] = "NO - "
adherents[32] = "NS - "
adherents[33] = "PG - 817\nPyrénées Gascogne"
adherents[34] = "RE - "
adherents[35] = "RP - 839\nSud Rhône Alpes"
adherents[36] = "SM - "
adherents[37] = "TO - "
adherents[38] = "TP - "
adherents[39] = "VF - "
adherents[40] = ""
adherents[41] = ""
adherents[42] = ""
adherents[43] = ""
adherents[44] = ""
adherents[45] = "NEHOM"
adherents[46] = "Ref v1"
adherents[47] = "DevTU"
adherents[48] = "VMOE"
adherents[49] = "VMOA"
adherents[50] = ""
adherents[51] = ""
adherents[52] = ""
adherents[53] = ""
adherents[54] = ""

actions[0] = "Connexion serveur BO"
actions[1] = ""
actions[2] = "Client SQL v1"
actions[3] = "Client SQL v2"
actions[4] = ""
actions[5] = "Deski 2 tiers v1"
actions[6] = "Deski 3 tiers v1"
actions[7] = "Designer v1"
actions[8] = "CMC v1"
actions[9] = "Infoview v1"
actions[10] = "Query builder v1"
actions[11] = ""
actions[12] = "Deski 2 tiers v2"
actions[13] = "Deski 3 tiers v2"
actions[14] = "Designer v2"
actions[15] = "CMC v2"
actions[16] = "Query builder v2"
actions[17] = ""
actions[18] = "Répertoire univers"
actions[19] = "Répertoire rapports"
actions[20] = ""
actions[21] = "Remedy"
